name: CI

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || format('{0}-{1}', github.ref, github.run_number) }}
  cancel-in-progress: true

jobs:
  # CI matrix - runs the job in lagom-template.yml with different configurations.
  Lagom:
    name: ${{ matrix.os_name }}, ${{ matrix.arch }}, ${{ matrix.build_preset }}, ${{ matrix.toolchain }}

    strategy:
      fail-fast: false
      matrix:
        os_name: ['Linux']
        arch: ['x86_64']
        build_preset: ['Release']
        toolchain: ['GNU']
        clang_plugins: [false]
        runner_label: ['ubuntu-latest']

        include:
          - os_name: 'Linux'
            arch: 'x86_64'
            build_preset: 'Release'
            toolchain: 'Clang'
            clang_plugins: true
            runner_label: 'ubuntu-latest'

          - os_name: 'macOS'
            arch: 'arm64'
            build_preset: 'Release'
            toolchain: 'Clang'
            clang_plugins: false
            runner_label: 'macos-latest'

    secrets: inherit
    uses: ./.github/workflows/lagom-template.yml
    with:
      toolchain: ${{ matrix.toolchain }}
      os_name: ${{ matrix.os_name }}
      runner_label: ${{ matrix.runner_label }}
      arch: ${{ matrix.arch }}
      build_preset: ${{ matrix.build_preset }}
      clang_plugins: ${{ matrix.clang_plugins }}
